### PR TITLE
Fix update balance genesis

### LINKED ISSUE #29: Reconciliation failed for genesis block account
**Describe the bug**
I have a blockchain which contains a transaction in the genesis block. This transaction contains a single output going to an address. I have found that the reconciliation step fails, expecting
computed balance to be twice the node balance (which is simply just the only output from the genesis transaction). The failure log shows, for example:

`Reconciliation failed for ss1q7q3h4chglps004u3yn79z0cp9ed24rfr9dn5nv at 0 computed: 4004420000HNS node: 2002210000HNS`

**To Reproduce**

* Create a genesis block containing a transaction generating an output to an address.

* Run `rosetta-cli check`

**Expected behavior**

* Check fails with the reconciliation expecting a balance equal to double the node balance.

**Additional context**

`rosetta-cli version v0.2.3, go version v0.2.3 on ubuntu linux, bionic`

### PR DESCRIPTION
**Pull request by tuxcanfly**
Fixes #29 .

### Motivation
Fixes a bug in genesis account balance which is reported as twice the existing amount.

### Solution
When UpdateBalance is called with `change.Block = parentBlock = genesisBlock`, `existingValue`
is already accounted for in the `AccountBalance`. Avoid double counting this by initializing "existingValue" to zero.

### Open questions
When also using a genesis balance bootstrap, it appears that the bootstrap is overriden and only the balance from the genesis block is returned. Before investigating further, I'd like to confirm what should be the expected behavior here. FWIW considering one or the other higher priority feels like a better solution. The other solution might be adding both the balances, which seems confusing.

### CODE REVIEW

**Comment by patrick-ogrady** [comment]
Seeing this `coverage` CI error now...very weird. Taking a deeper look now @tuxcanfly!

**Comment by patrick-ogrady** [comment]
The `Makefile` does include the `-repotoken`: https://github.com/coinbase/rosetta-cli/blob/1f0d9c523088a77d9f77e03b0d66a31f2d75a563/Makefile#L34

Still investigating...

**Comment by tuxcanfly** [comment]
Possible that token doesn't go through because I'm not a team member or something? That or Github hates me :laughing:

**Comment by patrick-ogrady** [comment]
> Possible that token doesn't go through because I'm not a team member or something? That or Github hates me 😆

Yeah this is exactly it...related to a setting in our circle config. Let me do some digging here and get back to you shortly. Thanks for putting up the PR!

**Comment by patrick-ogrady** [comment]
If you rebase onto master @tuxcanfly, this coverage check should pass. I just merged a fix for PRs from forked repositories (#31).

**Comment by patrick-ogrady** [comment]
Alright looked like that worked 🎉 ...will review the code shortly

File: internal/storage/block_storage.go [hunk 1]
```diff
@@ -490,14 +490,18 @@ func (b *BlockStorage) UpdateBalance(
 	}
 
 	var existingValue string
-	if exists {
+	switch {
```
Comment (patrick-ogrady) [inline internal/storage/block_storage.go:493]: > When also using a genesis balance bootstrap, it appears that the bootstrap is overriden and only the balance from the genesis block is returned. Before investigating further, I'd like to confirm what should be the expected behavior here. FWIW considering one or the other higher priority feels like a better solution. The other solution might be adding both the balances, which seems confusing.

I believe the preference here should be:
```suggestion
	switch {
	case exists: // this could happen if balances are bootstrapped and should not be overridden
	case parentBlock != nil && change.Block.Hash == parentBlock.Hash:
	default:
	}
```

File: internal/storage/block_storage_test.go [hunk 2]
```diff
@@ -343,7 +350,11 @@ func TestBalance(t *testing.T) {
 			Value:    "-1000",
 			Currency: currency,
 		}
-		mockHelper = &MockBlockStorageHelper{}
+		mockHelper = &MockBlockStorageHelper{
```
Comment (patrick-ogrady) [inline internal/storage/block_storage_test.go:353]: You shouldn't need to make any modifications to the `MockBlockStorageHelper` to implement this test.

Because the account key doesn't exist, we shouldn't hit any calls to the helper.

Comment (tuxcanfly) [reply internal/storage/block_storage_test.go:353]: You are right after the new switch case, this won't be hit. However, this will be help catch regressions, because without the fix, the helper will be called and it needs to return a positive balance for genesis accounts. Without this it would return zero, hiding the test failure.

Comment (patrick-ogrady) [reply internal/storage/block_storage_test.go:353]: 🤦 ahhhh yeah I gotcha...great call.

You could accomplish the same thing by using the already existing `AccountBalanceAmount` field (however, I see how adding the ability to stub specific account balances will be useful):
```suggestion
		mockHelper = &MockBlockStorageHelper{
		  AccountBalanceAmount: "100",
		}
```

I thought that deprecating `AccountBalanceAmount` may be a good idea but it is still useful (to stub any account amount).

Comment (patrick-ogrady) [reply internal/storage/block_storage_test.go:353]: I just included this suggestion to show other ways to do this ^^ but your change allows for more powerful testing later(preferred).

File: internal/storage/block_storage.go [hunk 3]
```diff
@@ -490,14 +490,21 @@ func (b *BlockStorage) UpdateBalance(
...
+	// this could happen if balances are bootstrapped and should not be overridden
```
Comment (patrick-ogrady) [inline internal/storage/block_storage.go:494]: Nit: we should capitalize the first letter in all comments on their own line (should've done this in the suggestions...didn't know you were going to use directly)

**Comment by patrick-ogrady** [comment]
Left one small nit on comment capitalization @tuxcanfly ... otherwise looks ready to go! Nice work!

File: internal/storage/block_storage.go (hunk 3 above)
Comment (tuxcanfly) [reply internal/storage/block_storage.go]: Fixed. :+1:

**Comment by tuxcanfly** [comment]
@patrick-ogrady Done :+1:

**Comment by patrick-ogrady** [comment]
Congrats @tuxcanfly! First external contribution!

**Comment by patrick-ogrady** [comment]
Release containing the fix: https://github.com/coinbase/rosetta-cli/releases/tag/v0.2.4
