### PR TITLE
Fix typos in types.go

### LINKED ISSUE #252: "Discrepancy" misspelled in types.go file
**Describe the bug**
`Discrepancy` is misspelled in the types.go file in the `InactiveDiscrepancySearchDisabled` type.

**To Reproduce**
Read the file.

**Expected behavior**
Discrepancy should be spelled correctly.

### PR DESCRIPTION
**Pull request by racbc**
Fixed misspelling of the word `discrepancy` in the `InactiveDiscrepancySearchDisabled` type in the types.go file.

Fixes #252.

### Motivation
Improve spelling in the code.

### Solution
Spelled `discrepancy` correctly.

### Open questions
This is my first PR, so please let me know whether I completed the process correctly. TIA.

### CODE REVIEW

File: configuration/types.go [hunk 1]
```diff
@@ -278,11 +278,11 @@ type DataConfiguration struct {
...
 	ReconciliationDrainDisabled bool `json:"reconciliation_drain_disabled"`
 
-	// InactiveDiscrepencySearchDisabled is a boolean indicating if a search
-	// should be performed to find any inactive reconciliation discrepencies.
+	// InactiveDiscrepancySearchDisabled is a boolean indicating if a search
+	// should be performed to find any inactive reconciliation discrepancies.
 	// Note, a search will never be performed if historical balance lookup
 	// is disabled.
-	InactiveDiscrepencySearchDisabled bool `json:"inactive_discrepency_search_disabled"`
+	InactiveDiscrepancySearchDisabled bool `json:"inactive_discrepancy_search_disabled"`
```
Comment (shrimalmadhur) [inline configuration/types.go:285]: You need to change all the references where this is being used.

Comment (racbc) [reply configuration/types.go:285]: This was updated in the b6b506e commit. However, for some reason, GitHub thinks it's an unverified merge.

**Review by shrimalmadhur — APPROVED** [review]
